### ISSUE TITLE
Enhance random source

### ISSUE THREAD

**Issue by kim201212** [dsrvlabs/dsrv-kzg-ceremony#15]
# Random Spec.

> - Link : https://github.com/ethereum/kzg-ceremony-specs/blob/master/docs/participant/participant.md#generating-randomness

## Generating randomness

The randomness that each participant contributes to a set of Powers of Tau is in the form of an integer in the range `(1, bls.r)`.

The participant MUST generate 4 different secrets from a _cryptographically-secure pseudo-random number generator_ (CSPRNG) of their choosing.

Each secret MUST meet the following requirements:
- Sourced from a CSPRNG
- Contain at least 255 bits of entropy
- Be different from the other 3 secrets used in the other sub-ceremonies
- Be cleared from memory after the contribution is complete

Furthermore, each secret SHOULD meet the following requirements:
- Be uniformly distributed across $\mathbb{F}_r$. (i.e. avoid modulo bias with respect to `bls.r`).

### `KeyGen`
A good method for meeting the above requirements would be to make use of the `KeyGen` function offered by all compliant BLS libraries. This function takes in a seed of at least 32 bytes and returns a uniformly sampled integer of $\mathbb{F}_r$.

# Task

- [x] Generate randomness for each contribution
- [x] Receive seed words with a flag
- [ ] Apply mnemonic words

**Comment by rootwarp** [comment]
@kim201212 Please describe the spec of the random source.
It could be helpful to debug together.

**Comment by rootwarp** [comment]
@kim201212 I know you have already done this issue, but what do you think expanding this issue by doing below?

https://github.com/dsrvlabs/czg-keremony/blob/f49341086590fed830d4b141c3785611c208a9f8/index.js#L142-L146

**Comment by kim201212** [comment]
> @kim201212 I know you have already done this issue, but what do you think expanding this issue by doing below?
> 
> https://github.com/dsrvlabs/czg-keremony/blob/f49341086590fed830d4b141c3785611c208a9f8/index.js#L142-L146

That's a great idea!
